// <auto-generated />
namespace Kiru8th.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202204140558561_AddNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
